#!/bin/bash
# This Works is placed under the terms of the Copyright Less License,
# see file COPYRIGHT.CLL.  USE AT OWN RISK, ABSOLUTELY NO WARRANTY.

{
cat <<EOF
/* !DO NOT EDIT!  Automatically generated by $0
 *
 * This Works is placed under the terms of the Copyright Less License,
 * see file COPYRIGHT.CLL.  USE AT OWN RISK, ABSOLUTELY NO WARRANTY.
 */

EOF
for a in cmd/*.h
do
	printf '#include "cmd/%s"\n' "${a##*/}"
done
} > cmd.h
