/* !DO NOT EDIT!  Automatically generated by ./cmd.sh
 *
 * This Works is placed under the terms of the Copyright Less License,
 * see file COPYRIGHT.CLL.  USE AT OWN RISK, ABSOLUTELY NO WARRANTY.
 */

#include "cmd/help.h"
#include "cmd/ls.h"
